name: rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - ipywidgets
  - jupyter_contrib_nbextensions
  - rise
  - pip
  - pip:
      - ubit_kernel